###################################################################################
# DO NOT EDIT THIS FILE. This is the main script to run Part C of the assignment. #
###################################################################################

###################################################################################
# This script acts as an entry point for LM Training.
# Data set will be available in ./data/ folder.
# There are two options to run the script:
# 1. Train tokenizer with `bash run_partc.sh --train-tokenizer``
# 2. Train the model with `bash run_partc.sh --train-model``
###################################################################################

# Data is present in the ./data/ folder. However, we can potentially change the data location during final evaluation.

# Check if the user provided an argument
if [ "$#" -ne 1 ]; then
    echo "Usage: bash run_partc.sh --train-tokenizer|--train-model"
    exit 1
fi

export WANDB_API_KEY=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

# Check which argument was provided and run the corresponding script
if [ "$1" == "--train-tokenizer" ]; then
    echo "Using the pretrained tokenizer provided in ./partb/final_tokenizer/ for model training."
    echo "No need to train the tokenizer again."

    # UNCOMMENT the line below to train the tokenizer.
    echo "Training the tokenizer..."
    python -m partb.train_tokenizer --input_corpus_path ./data/hindi_mid_corpus.txt \
      --train_path ./data/train.txt \
      --output_tokenizer_path ./partb/final_tokenizer/ --vocab_size 10000

elif [ "$1" == "--train-model" ]; then
    echo "Training the model..."
    python -m partc.train_model --train_path ./data/hindi_mid_corpus.txt \
        --valid_path ./data/valid_mid_corpus.txt \
        --tokenizer_path ./partb/final_tokenizer/ \
        --output_model_path ./partc/final_model/ --config_path ./partc/baseline.json

else
    echo "Invalid argument. Use --train-tokenizer or --train-model."
    exit 1
fi